version: '3.8'

services:
  jobmanager:
    image: apache/flink:1.17.1-scala_2.12
    container_name: jobmanager
    ports:
      - '8082:8081'
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager
    networks:
      - flink-network

  taskmanager:
    image: apache/flink:1.17.1-scala_2.12
    container_name: taskmanager
    depends_on:
      - jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager
    networks:
      - flink-network

  submit:
    build:
      context: ./submit
    container_name: pyflink-submit
    depends_on:
      - jobmanager
    volumes:
      - ./jobs:/opt/pyjobs
    command:
      [
        'bash',
        '-c',
        './wait-for-jobmanager.sh && flink run -py /opt/pyjobs/telemetry_job.py -pyexec python3 -m jobmanager:8081'
      ]
    networks:
      - flink-network

networks:
  flink-network:
    external: true
